stalker/stalker/urls.py
""" stalker project URL config """

from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('stalker_app.urls')),
    url(r'^', include('stalker_app_api.urls')),
]

stalker/stalker_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'stalker_app'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^maps/$', views.maps, name='maps'),
    url(r'^users/$', views.users, name='users'),
]

stalker/stalker_app_api/urls.py
from django.conf.urls import url

from . import views

app_name = 'stalker_app_api'

urlpatterns = [
    url(r'^auth_login/$', views.auth_login, name='auth_login'),
    url(r'^auth_logout/$', views.auth_logout, name='auth_logout'),
    url(r'^sign_up_attempt/$', views.sign_up_attempt, name='sign_up_attempt'),
    url(r'^mark_location/$', views.mark_location, name='mark_location'),
    url(r'^locations/$', views.get_locations_for_user, name='get_locations_for_user'),
    url(r'^get_users/$', views.get_users, name='get_users'),
    url(r'^change_user_admin/$', views.change_user_admin, name='change_user_admin'),
    url(r'^new_user/$', views.new_user, name='new_user'),
]

stalker/stalker_app/models.py
""" Models in stalker_app """
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractBaseUser
from django.db.models import Model, CharField, IntegerField, ForeignKey, \
    BooleanField, DateTimeField, EmailField, DateField, CASCADE, DecimalField
from django.core.validators import EmailValidator, MaxLengthValidator, \
    MinLengthValidator, URLValidator, MaxValueValidator, MinValueValidator
from django.utils import timezone

from . managers import UserManager

class Date(Model):
    """ Abstract class to store common attributes for all 'stalker_app' models.

        Use: Inherit from this class if you want your data timestamped at
        creation and at each update. """

    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    class Meta():
        abstract = True


class User(AbstractBaseUser, Date):
    """ Model containing all user attributes.Uses 'UserManager' from managers
    """

    objects = UserManager()
    name = CharField(
        max_length=64,
        validators=[
                MaxLengthValidator(100,  message="Name must be at most 100 \
                                   characters"),
                MinLengthValidator(3,   message="Name must be at least 3 \
                                   characters"),
        ])
    email = EmailField(
        max_length=100,
        unique=True,
        validators=[
                MaxLengthValidator(100,  message="Email must be at most 100 \
                                   characters"),
                MinLengthValidator(3,   message="Email must be at least 3 \
                                   characters"),
                EmailValidator(message="Invalid email adress"),
        ],
    )
    address = CharField(
        max_length=100,
        validators=[
                MaxLengthValidator(100,  message="Address must be at most 100 \
                                   characters"),
                MinLengthValidator(3,   message="Address must be at least 3 \
                                   characters"),
        ])
    password = CharField(max_length=1000)
    is_super_admin = BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'is_super_admin']

    date_joined = DateTimeField(default=timezone.now)
    is_active = BooleanField(default=True)
    is_admin = BooleanField(default=False)
    is_staff = BooleanField(default=False)


    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    class Meta:
        db_table = 'users'


class Coordinate(Date):
    latitude = DecimalField(validators=[
            MaxValueValidator(90,  message="Latitude must be up to 90"),
            MinLengthValidator(-90,   message="Latitude must be a minimum of \
                -90")],
            max_digits=10, decimal_places=8, default=0)
    longitude = DecimalField(validators=[
            MaxValueValidator(180,  message="Longitude must be up to 180"),
            MinLengthValidator(-90,   message="Longitude must be a minimum of \
                -180")],
            max_digits=10, decimal_places=8, default=0)

    class Meta:
        db_table = 'coordinates'

stalker/stalker_app/forms.py
""" all the forms in 'app' application """

import datetime
from django.utils import timezone
from django.forms import Form, ModelForm, CharField, TextInput, PasswordInput, \
    EmailField, BooleanField, Textarea, CheckboxInput, URLField, ChoiceField, \
    MultipleChoiceField, DateTimeField, HiddenInput
from django.core.validators import EmailValidator, MaxLengthValidator, \
    MinLengthValidator

from .models import User

class BaseUserForm(ModelForm):
    """ form used to edit a specifc user object or create a new one """

    class Meta:
        model = User
        fields = ('name', 'email', 'address')
        widgets =  {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'email': TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'address': TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
        }
        labels = {
            'name': 'Name:',
            'email': 'Email:',
            'address': 'Address',
        }
        error_messages = {
            'name': {
                'max_length': "Name must be at most 64 characters",
                'min_length': "Name must be at least 3 characters",
            },
            'description': {
                'max_length': "Email must be at most 64 characters",
                'min_length': "Email must be at least 3 characters",
            },
        }


class RegistrationForm(BaseUserForm):
    """ extends the BaseUserForm to create a for for adding a new_user.If form
        doesn't raise errors a new user is saved """

    password = CharField(
        label='Password:',
        widget=PasswordInput(
            attrs={
               'class': 'form-control',
               'id': 'login-password',
               'placeholder': 'Password',
            }
        ),
        validators=[
            MaxLengthValidator(
                  64,
                  message="Password must be at most 64 characters"
            ),
            MinLengthValidator(
                5,
                message="Password must be at least 5 characters long"
            )
        ]
    )

    confirm_password = CharField(
        label='Confirm password:',
        widget=PasswordInput(
            attrs={
               'class': 'form-control',
               'placeholder': 'Confirm Password',
            }
        ),
    )
    def clean(self):
        """ method to add a custom error to the form if the data from the
            password field does't match confirm password field data """
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            self.add_error('confirm_password', "Passwords don't match")

        return cleaned_data

stalker/stalker_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.conf import settings
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test

from stalker_app_api.forms import RegistrationForm, RegistrationFormAdmin
from .helper_functions import is_super_admin

def home(request):
    return render(request, 'stalker_app/home.html', {})

def login(request):
    context = {'login_api': reverse('stalker_app_api:auth_login')}
    if request.user.is_authenticated():
        return HttpResponseRedirect('stalker_app/home.html')
    return render(request, 'stalker_app/login.html', context)

def sign_up(request):
    context = {
        'registration_form': RegistrationForm(),
        'sign_up_url': reverse('stalker_app_api:sign_up_attempt'),
    }
    return render(request, 'stalker_app/sign_up.html', context)


@login_required
def maps(request):
    context = {
        'map_api_key': settings.MAPS_API_KEY,
        'mark_location_api': reverse('stalker_app_api:mark_location'),
        'get_locations_api': reverse('stalker_app_api:get_locations_for_user'),
        'get_users_api': reverse('stalker_app_api:get_users'),
    }
    return render(request, 'stalker_app/maps.html', context)


@user_passes_test(is_super_admin, login_url='/')
@login_required
def users(request):
    context = {
        'get_users_api': reverse('stalker_app_api:get_users'),
        'change_user_admin_api': reverse('stalker_app_api:change_user_admin'),
        'registration_form': RegistrationFormAdmin(),
        'new_user_url': reverse('stalker_app_api:new_user')
    }
    return render(request, 'stalker_app/users.html', context)

stalker/stalker_app/templates/stalker_app/home.html
{% extends 'stalker_app/layout.html' %}

<head>
  {% block head_content %}
    {{ block.super }}
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/stalker_app/css/home.css" />
      <link rel="stylesheet" href="../../static/stalker_app/css/_carousel.css" />
  {% endblock %}
</head>

{% block content %}
  <div class="container-fluid carousel-home">
    {% include 'partials/_carousel.html' %}
  </div>
  <div class="container-fluid home-content">
    <div class="container bounce">
      <span class="glyphicon glyphicon-menu-down bounce-icon"></span>
    </div>
    <div class="container-fluid ">
        lala
    </div>
  </div>
  {% block javascript %}
    {{ block.super }}
  {% endblock %}
{% endblock %}

stalker/stalker_app/templates/stalker_app/layout.html
{% load bootstrap3 %}
{% bootstrap_css %}

<head>
  {% block head_content %}
    <meta charset=“UTF-8“ />
    <!-- <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/css/bootstrap-notify.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="../../static/stalker_app/css/common.css" />
  {% endblock %}
</head>

<body id="particles-js">
  {% block header %}
    <nav class="navbar stalker-navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'stalker_app:home' %}">
            <span class="glyphicon glyphicon-home"></span>
            Stalker
          </a>
        </div>
        <!-- <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Page 1</a></li>
          <li><a href="#">Page 2</a></li>
          <li><a href="#">Page 3</a></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
         {% if request.user.is_authenticated %}
           {% if request.user.is_super_admin %}
             <li><a href="{% url 'stalker_app:users' %}"><span class="glyphicon glyphicon-user"></span> Users</a></li>
           {% endif %}
            <li><a href="{% url 'stalker_app:maps' %}"><span class="glyphicon glyphicon-map-marker"></span> Maps</a></li>
            <li><a href="#" class="logout-button" data-logout-url="{% url 'stalker_app_api:auth_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
         {% else %}
          <li><a href="{% url 'stalker_app:sign_up' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'stalker_app:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
         {% endif %}
        </ul>
      </div>
    </nav>
    {% if request.user.is_authenticated %}

    {% endif %}
  {% endblock %}

  {% block content %}
    {% block javascript %}
      {% bootstrap_javascript %}
      <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
      <script src="../../static/stalker_app/js/common.js" ></script>
      <script src="../../static/stalker_app/js/auth/logout.js" ></script>
    {% endblock %}
  {% endblock %}
</body>

stalker/stalker_app/templates/stalker_app/login.html
{% extends 'stalker_app/layout.html' %}

{% block header %}
  {{ block.super }}
  <link rel="stylesheet" href="../../static/stalker_app/css/login.css" />
{% endblock %}
{% block content %}
  <div class="particlesJS login-particles">
    <div class="container login-form-container" data-aos="zoom-in">
      <form class="login-form">
        <div class="input-group">
          <span class="input-group-addon first-addon"><i class="glyphicon glyphicon-user"></i></span>
          <input id="email" type="text" class="form-control" name="email" placeholder="Email">
        </div>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <input id="password" type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <div class="submit-button login-submit text-center">
          <button type="button" class="btn btn-warning" data-request="{{ login_api }}">
            <span class="glyphicon glyphicon-log-in button-glyph"></span>Log in
          </button>
        </div>
      </form>
		</div>
  </div>
  {% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <script src="../../static/stalker_app/js/particles/app.js" ></script>
    <script src="../../static/stalker_app/js/auth/login.js" ></script>
  {% endblock %}
{% endblock %}

stalker/stalker_app/templates/stalker_app/maps.html
{% extends 'stalker_app/layout.html' %}

<head>
  {% block head_content %}
    {{ block.super }}
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/stalker_app/css/common.css" />
    <link rel="stylesheet" href="../../static/stalker_app/css/maps.css" />
  {% endblock %}
</head>

{% block content %}
  <div class="map-content">
    <div class="container-fluid map-controls">
      <div class="container row vertical-align">
        <div class="buttons col-sm-10">
          <button type="button" class="btn btn-info map-control get-current-location">
            <span class="glyphicon glyphicon-cloud button-glyph"></span>Current Location
          </button>
          <button type="button" class="btn btn-info map-control get-own-locations" data-get-locations-url="{{ get_locations_api }}">
            <span class="glyphicon glyphicon-road button-glyph"></span>Your marked road
          </button>
          <button type="button" class="btn btn-info map-control mark-location" data-mark-location-url="{{ mark_location_api }}">
            <span class="glyphicon glyphicon-map-marker button-glyph"></span>Mark current location
          </button>
        </div>
        <div class="select col-sm-2">
          <select class="select-user-map pull-right" data-get-user-map="{{ get_locations_api }}" data-get-users="{{ get_users_api }}">
          </select>
        </div>
      </div>
    </div>
    <div class="container-fluid map-container" >
      <div id="map" class="map google-map"></div>
    </div>
    <div class="container loader-container">
      <div class="loader"></div>
      <div class="loader-text">Loading map ...</div>
    </div>
  </div>
  {% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{ map_api_key }}&callback=initMap"
    async defer></script>
    <script src="../../static/stalker_app/js/maps/maps.js" ></script>
  {% endblock %}
{% endblock %}

stalker/stalker_app/templates/stalker_app/sign_up.html
{% extends 'stalker_app/layout.html' %}
{% load bootstrap3 %}

{% block header %}
  {{ block.super }}
  <link rel="stylesheet" href="../../static/stalker_app/css/sign_up.css" />
{% endblock %}

{% block content %}

  <div class="sign-up-content particlesJS login-particles">
    <div class="container sign-up-form-container" data-aos="zoom-in">
      <form data-sign-up="{{ sign_up_url }}" class="sign-up-form">
        {% bootstrap_form registration_form %}
      </form>
      <div class="submit-button login-submit text-center">
        <button type="button" class="btn btn-warning sign-up">
          <span class="glyphicon glyphicon-user button-glyph"></span>Sign up</button>
      </div>
    </div>
  </div>
  {% block javascript %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <script src="../../static/stalker_app/js/particles/app.js" ></script>
    <script src="../../static/stalker_app/js/user/sign_up.js" ></script>
  {% endblock %}
{% endblock %}

stalker/stalker_app/templates/stalker_app/users.html
{% extends 'stalker_app/layout.html' %}
{% load bootstrap3 %}

<head>
  {% block head_content %}
    {{ block.super }}
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/stalker_app/css/common.css" />
    <link rel="stylesheet" href="../../static/stalker_app/css/users.css" />
  {% endblock %}
</head>

{% block content %}
  <div class="container button-container">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#newUserModal">
      <span class="glyphicon glyphicon-plus button-glyph"></span>New User</button>
  </div>
  <div class="container table-container">
    <div class="app-table users-table" data-get-users="{{ get_users_api }}" data-change-user-admin="{{ change_user_admin_api }}">
      <div class="row app-table-title">
        <div class="app-table-data-title col-xs-3 col-sm-3 col-md-3 col-lg-2 col-xl-2">
          Name
        </div>
        <div class="app-table-data-title col-xs-4 col-sm-4 col-md-3 col-lg-4 col-xl-4">
          Email
        </div>
        <div class="app-table-data-title col-xs-2 col-sm-2 col-md-2 col-lg-3 col-xl-3">
          Address
        </div>
        <div class="app-table-data-title text-center col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
          Is admin
        </div>
        <div class="app-table-data-title col-xs-1 col-sm-1 col-md-2 col-lg-1 col-xl-1">
          More details
        </div>
      </div>
      <div class="row app-table-content">
      </div>
    </div>
  </div>
  <div id="newUserModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center">Add a new user</h4>
        </div>
        <div class="modal-body">
          <form action="" class="new-user-form">
            {% bootstrap_form registration_form %}
          </form>
        </div>
        <div class="modal-footer">
          <div class="modal-buttons">
            <button type="button" class="btn btn-success submit-new-user">
              <span class="glyphicon glyphicon-ok button-glyph"></span>Submit user</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block javascript %}
    {{ block.super }}
    <script src="../../static/stalker_app/js/user/users.js" ></script>
  {% endblock %}
{% endblock %}